/**
 * Per-action GCD recast data and the speed formula. Port of OverlayPluginAddon's ActionData.cs.
 *
 * This is the one part of the GCD calculation that cannot be observed from a log: the category
 * table says which actions are GCDs but not how long they occupy it, and xivanalysis maintains
 * that by hand (js/gcd/actions-data.js, generated by tools/Build-ActionData.js). Anything absent
 * from the table is a plain 2.5s GCD that scales with the player's speed stat, which is the
 * overwhelming majority.
 *
 * Pure: no DOM, no globals. Browser: window.GcdActionData. Node: require().
 */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.GcdActionData = factory();
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  const BASE_GCD_MS = 2500;

  /**
   * Extra delay before the next GCD when a cast is at least a full GCD long - "caster tax".
   * Matches ANIMATION_LOCK in xivanalysis.
   */
  const ANIMATION_LOCK_MS = 100;

  const SpeedAttribute = Object.freeze({
    /** The recast is a flat number no matter how much speed the player has (dance steps). */
    None: 'NONE',
    SkillSpeed: 'SKILL_SPEED',
    SpellSpeed: 'SPELL_SPEED',
  });

  /** The default every action not in the table follows. */
  const DEFAULT_DEF = Object.freeze({
    id: 0,
    name: '',
    recast: BASE_GCD_MS,
    castTime: 0,
    speedAttribute: SpeedAttribute.SkillSpeed,
  });

  const num = (v) => {
    const n = Number(v);
    return Number.isFinite(n) ? n : undefined;
  };

  function parseAttribute(attribute) {
    switch (attribute) {
      case 'SKILL_SPEED': return SpeedAttribute.SkillSpeed;
      case 'SPELL_SPEED': return SpeedAttribute.SpellSpeed;
      default: return SpeedAttribute.None;
    }
  }

  class ActionData {
    constructor() {
      this.byId = new Map();
      this.speedStatuses = new Map();
      /**
       * For a haste status that only quickens some actions, the ids it applies to. Inspiration
       * hastens a Pictomancer's aetherhue spells and Star Prism and nothing else, and the hammer
       * combo pressed inside Starry Muse must not inherit its 0.75.
       */
      this.speedStatusLimits = new Map();
      this.loadError = null;
    }

    get actionCount() { return this.byId.size; }
    get speedStatusCount() { return this.speedStatuses.size; }

    /** The action's row, or the 2.5s / skill-speed default. */
    get(actionId) { return this.byId.get(actionId) || DEFAULT_DEF; }

    /** Whether the table has a real entry, or get() fell back to the default. */
    knows(actionId) { return this.byId.has(actionId); }

    /**
     * Haste multiplier one status applies to one action: 1 when the status does not affect speed,
     * or affects speed but not this action.
     */
    speedModifierOf(statusId, actionId) {
      const modifier = this.speedStatuses.get(statusId);
      if (modifier === undefined) return 1;
      const only = this.speedStatusLimits.get(statusId);
      if (only && !only.has(actionId)) return 1;
      return modifier;
    }

    isSpeedStatus(statusId) { return this.speedStatuses.has(statusId); }
  }

  /** @param table the object js/gcd/actions-data.js exports (the actions.json shape). */
  function load(table) {
    const data = new ActionData();
    try {
      if (!table || typeof table !== 'object') {
        data.loadError = 'action table missing (js/gcd/actions-data.js not loaded)';
        return data;
      }

      for (const entry of Array.isArray(table.actions) ? table.actions : []) {
        const id = num(entry && entry.id);
        if (id === undefined) continue;
        const recast = num(entry.recast);
        const castTime = num(entry.castTime);
        data.byId.set(id, {
          id,
          name: String(entry.name || ''),
          recast: recast === undefined ? BASE_GCD_MS : recast,
          castTime: castTime === undefined ? 0 : castTime,
          speedAttribute: parseAttribute(entry.speedAttribute),
        });
      }

      for (const entry of Array.isArray(table.speedStatuses) ? table.speedStatuses : []) {
        const id = num(entry && entry.id);
        const modifier = num(entry && entry.speedModifier);
        if (id === undefined || modifier === undefined || modifier <= 0) continue;
        data.speedStatuses.set(id, modifier);

        if (Array.isArray(entry.limitedTo) && entry.limitedTo.length > 0) {
          const set = new Set();
          for (const a of entry.limitedTo) {
            const actionId = num(a);
            if (actionId !== undefined) set.add(actionId);
          }
          data.speedStatusLimits.set(id, set);
        }
      }
    } catch (e) {
      data.loadError = String((e && e.message) || e);
    }
    return data;
  }

  // ------------------------------------------------------------------ the speed formula
  //
  // Straight from xivanalysis' speedStatMapper, which in turn matches Allagan Studies. Both
  // directions are needed: observed intervals go one way to a stat, and the stat comes back the
  // other way as the recast of every action the player has, including ones whose base recast is
  // not 2.5s.

  const SUB_ATTRIBUTE_MINIMUM = 420;
  const STAT_DIVISOR = 2780;

  /** Turns an observed GCD length in milliseconds into the speed stat that produces it. */
  function speedStatFor(observedGcdMs) {
    return Math.floor(1 / 130 * STAT_DIVISOR * (1000 - 1000 * observedGcdMs / BASE_GCD_MS)) + SUB_ATTRIBUTE_MINIMUM;
  }

  /** Applies a speed stat to a base duration, in milliseconds. */
  function adjustedDuration(speedStat, baseDurationMs) {
    const attributeMultiplier = 1000 - Math.floor(130 * (speedStat - SUB_ATTRIBUTE_MINIMUM) / STAT_DIVISOR);
    const adjusted = Math.floor(attributeMultiplier * baseDurationMs / 1000);

    // The haste and astral/umbral terms of the real formula are folded in by the caller as a
    // plain multiplier, so the remaining two floors reduce to centiseconds.
    return Math.floor(adjusted / 10) * 10;
  }

  return { load, speedStatFor, adjustedDuration, BASE_GCD_MS, ANIMATION_LOCK_MS, SpeedAttribute, DEFAULT_DEF };
});
