/*
 * Per-action GCD recast overrides and haste statuses, from xivanalysis. Read through
 * js/gcd/action-data.js.
 *
 * Generated by tools/Build-ActionData.js - do not hand-edit, re-run the script instead.
 */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else root.GcdActionTable = factory();
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';
  return {
  	"_generator": "tools/Build-ActionData.js - do not hand-edit, re-run the script instead",
  	"_source": "xivanalysis src/data/ACTIONS/root and src/data/STATUSES/root",
  	"_generatedAt": "2026-09-13",
  	"_recast": "Milliseconds the action occupies the GCD. Actions matching the 2500ms default AND scaling with a speed stat are omitted - the consumer assumes those.",
  	"_speedAttribute": "Absent means the recast does not scale with skill/spell speed at all (dance steps). Those intervals must not feed the speed estimate.",
  	"_limitedTo": "On a speed status: the only action ids it hastens. Absent means every GCD the player has.",
  	"_onGcd": "Every action id xivanalysis flags onGcd: true. Decides GCD-or-not ahead of the game category table, which files Ninja mudras/Ninjutsu, Monk meditations and Samurai Meditate as abilities although they roll the GCD.",
  	"baseGcd": 2500,
  	"jobSpeedModifiers": {
  		"MNK": 0.8,
  		"NIN": 0.85
  	},
  	"actions": [
  		{
  			"id": 125,
  			"name": "RAISE",
  			"job": "WHM",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 8000
  		},
  		{
  			"id": 128,
  			"name": "REPOSE",
  			"job": "WHM",
  			"recast": 2500,
  			"castTime": 2500
  		},
  		{
  			"id": 139,
  			"name": "HOLY",
  			"job": "WHM",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 2500
  		},
  		{
  			"id": 141,
  			"name": "FIRE_I",
  			"job": "BLM",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 2500
  		},
  		{
  			"id": 142,
  			"name": "BLIZZARD_I",
  			"job": "BLM",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 2500
  		},
  		{
  			"id": 147,
  			"name": "FIRE_II",
  			"job": "BLM",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 3000
  		},
  		{
  			"id": 152,
  			"name": "FIRE_III",
  			"job": "BLM",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 3500
  		},
  		{
  			"id": 154,
  			"name": "BLIZZARD_III",
  			"job": "BLM",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 3500
  		},
  		{
  			"id": 159,
  			"name": "FREEZE",
  			"job": "BLM",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 2800
  		},
  		{
  			"id": 162,
  			"name": "FLARE",
  			"job": "BLM",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 4000
  		},
  		{
  			"id": 173,
  			"name": "RESURRECTION",
  			"job": "SCH",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 8000
  		},
  		{
  			"id": 2259,
  			"name": "TEN",
  			"job": "NIN",
  			"recast": 500
  		},
  		{
  			"id": 2260,
  			"name": "NINJUTSU",
  			"job": "NIN",
  			"recast": 1500
  		},
  		{
  			"id": 2261,
  			"name": "CHI",
  			"job": "NIN",
  			"recast": 500
  		},
  		{
  			"id": 2263,
  			"name": "JIN",
  			"job": "NIN",
  			"recast": 500
  		},
  		{
  			"id": 2265,
  			"name": "FUMA_SHURIKEN",
  			"job": "NIN",
  			"recast": 1500
  		},
  		{
  			"id": 2266,
  			"name": "KATON",
  			"job": "NIN",
  			"recast": 1500
  		},
  		{
  			"id": 2267,
  			"name": "RAITON",
  			"job": "NIN",
  			"recast": 1500
  		},
  		{
  			"id": 2268,
  			"name": "HYOTON",
  			"job": "NIN",
  			"recast": 1500
  		},
  		{
  			"id": 2269,
  			"name": "HUTON",
  			"job": "NIN",
  			"recast": 1500
  		},
  		{
  			"id": 2270,
  			"name": "DOTON",
  			"job": "NIN",
  			"recast": 1500
  		},
  		{
  			"id": 2271,
  			"name": "SUITON",
  			"job": "NIN",
  			"recast": 1500
  		},
  		{
  			"id": 2272,
  			"name": "RABBIT_MEDIUM",
  			"job": "NIN",
  			"recast": 1500
  		},
  		{
  			"id": 3572,
  			"name": "AERO_III",
  			"job": "WHM",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 2500
  		},
  		{
  			"id": 3576,
  			"name": "BLIZZARD_IV",
  			"job": "BLM",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 2500
  		},
  		{
  			"id": 3577,
  			"name": "FIRE_IV",
  			"job": "BLM",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 2800
  		},
  		{
  			"id": 3603,
  			"name": "ASCEND",
  			"job": "AST",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 8000
  		},
  		{
  			"id": 7410,
  			"name": "HEAT_BLAST",
  			"job": "MCH",
  			"recast": 1500
  		},
  		{
  			"id": 7418,
  			"name": "FLAMETHROWER",
  			"job": "MCH",
  			"recast": 2500
  		},
  		{
  			"id": 7505,
  			"name": "VERTHUNDER",
  			"job": "RDM",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 5000
  		},
  		{
  			"id": 7507,
  			"name": "VERAERO",
  			"job": "RDM",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 5000
  		},
  		{
  			"id": 7509,
  			"name": "SCATTER",
  			"job": "RDM",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 5000
  		},
  		{
  			"id": 7523,
  			"name": "VERRAISE",
  			"job": "RDM",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 10000
  		},
  		{
  			"id": 7527,
  			"name": "ENCHANTED_RIPOSTE",
  			"job": "RDM",
  			"recast": 1500
  		},
  		{
  			"id": 7528,
  			"name": "ENCHANTED_ZWERCHHAU",
  			"job": "RDM",
  			"recast": 1500
  		},
  		{
  			"id": 7529,
  			"name": "ENCHANTED_REDOUBLEMENT",
  			"job": "RDM",
  			"recast": 2200,
  			"speedAttribute": "SKILL_SPEED"
  		},
  		{
  			"id": 7530,
  			"name": "ENCHANTED_MOULINET",
  			"job": "RDM",
  			"recast": 1500
  		},
  		{
  			"id": 7568,
  			"name": "ESUNA",
  			"job": "ROLE",
  			"recast": 2500
  		},
  		{
  			"id": 15997,
  			"name": "STANDARD_STEP",
  			"job": "DNC",
  			"recast": 1500
  		},
  		{
  			"id": 15998,
  			"name": "TECHNICAL_STEP",
  			"job": "DNC",
  			"recast": 1500
  		},
  		{
  			"id": 15999,
  			"name": "EMBOITE",
  			"job": "DNC",
  			"recast": 1000
  		},
  		{
  			"id": 16000,
  			"name": "ENTRECHAT",
  			"job": "DNC",
  			"recast": 1000
  		},
  		{
  			"id": 16001,
  			"name": "JETE",
  			"job": "DNC",
  			"recast": 1000
  		},
  		{
  			"id": 16002,
  			"name": "PIROUETTE",
  			"job": "DNC",
  			"recast": 1000
  		},
  		{
  			"id": 16003,
  			"name": "STANDARD_FINISH",
  			"job": "DNC",
  			"recast": 1500
  		},
  		{
  			"id": 16004,
  			"name": "TECHNICAL_FINISH",
  			"job": "DNC",
  			"recast": 1500
  		},
  		{
  			"id": 16191,
  			"name": "SINGLE_STANDARD_FINISH",
  			"job": "DNC",
  			"recast": 1500
  		},
  		{
  			"id": 16192,
  			"name": "DOUBLE_STANDARD_FINISH",
  			"job": "DNC",
  			"recast": 1500
  		},
  		{
  			"id": 16193,
  			"name": "SINGLE_TECHNICAL_FINISH",
  			"job": "DNC",
  			"recast": 1500
  		},
  		{
  			"id": 16194,
  			"name": "DOUBLE_TECHNICAL_FINISH",
  			"job": "DNC",
  			"recast": 1500
  		},
  		{
  			"id": 16195,
  			"name": "TRIPLE_TECHNICAL_FINISH",
  			"job": "DNC",
  			"recast": 1500
  		},
  		{
  			"id": 16196,
  			"name": "QUADRUPLE_TECHNICAL_FINISH",
  			"job": "DNC",
  			"recast": 1500
  		},
  		{
  			"id": 16476,
  			"name": "SIX_SIDED_STAR",
  			"job": "MNK",
  			"recast": 5000,
  			"speedAttribute": "SKILL_SPEED"
  		},
  		{
  			"id": 16491,
  			"name": "GOKA_MEKKYAKU",
  			"job": "NIN",
  			"recast": 1500
  		},
  		{
  			"id": 16492,
  			"name": "HYOSHO_RANRYU",
  			"job": "NIN",
  			"recast": 1500
  		},
  		{
  			"id": 16497,
  			"name": "AUTO_CROSSBOW",
  			"job": "MCH",
  			"recast": 2500
  		},
  		{
  			"id": 16498,
  			"name": "DRILL",
  			"job": "MCH",
  			"recast": 2500
  		},
  		{
  			"id": 16499,
  			"name": "BIOBLASTER",
  			"job": "MCH",
  			"recast": 2500
  		},
  		{
  			"id": 16504,
  			"name": "ARM_PUNCH",
  			"job": "MCH",
  			"recast": 2500
  		},
  		{
  			"id": 16505,
  			"name": "DESPAIR",
  			"job": "BLM",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 3000
  		},
  		{
  			"id": 16526,
  			"name": "IMPACT",
  			"job": "RDM",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 5000
  		},
  		{
  			"id": 18805,
  			"name": "TEN_KASSATSU",
  			"job": "NIN",
  			"recast": 500
  		},
  		{
  			"id": 18806,
  			"name": "CHI_KASSATSU",
  			"job": "NIN",
  			"recast": 500
  		},
  		{
  			"id": 18807,
  			"name": "JIN_KASSATSU",
  			"job": "NIN",
  			"recast": 500
  		},
  		{
  			"id": 18873,
  			"name": "FUMA_SHURIKEN_TCJ_TEN",
  			"job": "NIN",
  			"recast": 1000
  		},
  		{
  			"id": 18874,
  			"name": "FUMA_SHURIKEN_TCJ_CHI",
  			"job": "NIN",
  			"recast": 1000
  		},
  		{
  			"id": 18875,
  			"name": "FUMA_SHURIKEN_TCJ_JIN",
  			"job": "NIN",
  			"recast": 1000
  		},
  		{
  			"id": 18876,
  			"name": "KATON_TCJ",
  			"job": "NIN",
  			"recast": 1000
  		},
  		{
  			"id": 18877,
  			"name": "RAITON_TCJ",
  			"job": "NIN",
  			"recast": 1000
  		},
  		{
  			"id": 18878,
  			"name": "HYOTON_TCJ",
  			"job": "NIN",
  			"recast": 1000
  		},
  		{
  			"id": 18879,
  			"name": "HUTON_TCJ",
  			"job": "NIN",
  			"recast": 1500
  		},
  		{
  			"id": 18880,
  			"name": "DOTON_TCJ",
  			"job": "NIN",
  			"recast": 1500
  		},
  		{
  			"id": 18881,
  			"name": "SUITON_TCJ",
  			"job": "NIN",
  			"recast": 1500
  		},
  		{
  			"id": 24287,
  			"name": "EGEIRO",
  			"job": "SGE",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 8000
  		},
  		{
  			"id": 24290,
  			"name": "EUKRASIA",
  			"job": "SGE",
  			"recast": 1000
  		},
  		{
  			"id": 24291,
  			"name": "EUKRASIAN_DIAGNOSIS",
  			"job": "SGE",
  			"recast": 1500
  		},
  		{
  			"id": 24292,
  			"name": "EUKRASIAN_PROGNOSIS",
  			"job": "SGE",
  			"recast": 1500
  		},
  		{
  			"id": 24293,
  			"name": "EUKRASIAN_DOSIS",
  			"job": "SGE",
  			"recast": 1500
  		},
  		{
  			"id": 24308,
  			"name": "EUKRASIAN_DOSIS_II",
  			"job": "SGE",
  			"recast": 1500
  		},
  		{
  			"id": 24314,
  			"name": "EUKRASIAN_DOSIS_III",
  			"job": "SGE",
  			"recast": 1500
  		},
  		{
  			"id": 24380,
  			"name": "SOUL_SLICE",
  			"job": "RPR",
  			"recast": 2500
  		},
  		{
  			"id": 24381,
  			"name": "SOUL_SCYTHE",
  			"job": "RPR",
  			"recast": 2500
  		},
  		{
  			"id": 24387,
  			"name": "SOULSOW",
  			"job": "RPR",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 5000
  		},
  		{
  			"id": 24395,
  			"name": "VOID_REAPING",
  			"job": "RPR",
  			"recast": 1500
  		},
  		{
  			"id": 24396,
  			"name": "CROSS_REAPING",
  			"job": "RPR",
  			"recast": 1500
  		},
  		{
  			"id": 24397,
  			"name": "GRIM_REAPING",
  			"job": "RPR",
  			"recast": 1500
  		},
  		{
  			"id": 25793,
  			"name": "BLIZZARD_II",
  			"job": "BLM",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 3000
  		},
  		{
  			"id": 25794,
  			"name": "HIGH_FIRE_II",
  			"job": "BLM",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 3000
  		},
  		{
  			"id": 25795,
  			"name": "HIGH_BLIZZARD_II",
  			"job": "BLM",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 3000
  		},
  		{
  			"id": 25798,
  			"name": "SUMMON_CARBUNCLE",
  			"job": "SMN",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 2500
  		},
  		{
  			"id": 25814,
  			"name": "RUBY_OUTBURST",
  			"job": "SMN",
  			"recast": 3000,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 2800
  		},
  		{
  			"id": 25816,
  			"name": "EMERALD_OUTBURST",
  			"job": "SMN",
  			"recast": 1500
  		},
  		{
  			"id": 25817,
  			"name": "RUBY_RUIN_III",
  			"job": "SMN",
  			"recast": 3000,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 2800
  		},
  		{
  			"id": 25819,
  			"name": "EMERALD_RUIN_III",
  			"job": "SMN",
  			"recast": 1500,
  			"speedAttribute": "SPELL_SPEED"
  		},
  		{
  			"id": 25823,
  			"name": "RUBY_RITE",
  			"job": "SMN",
  			"recast": 3000,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 2800
  		},
  		{
  			"id": 25825,
  			"name": "EMERALD_RITE",
  			"job": "SMN",
  			"recast": 1500
  		},
  		{
  			"id": 25832,
  			"name": "RUBY_CATASTROPHE",
  			"job": "SMN",
  			"recast": 3000,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 2800
  		},
  		{
  			"id": 25834,
  			"name": "EMERALD_CATASTROPHE",
  			"job": "SMN",
  			"recast": 1500
  		},
  		{
  			"id": 25837,
  			"name": "SLIPSTREAM",
  			"job": "SMN",
  			"recast": 3500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 3000
  		},
  		{
  			"id": 25855,
  			"name": "VERTHUNDER_III",
  			"job": "RDM",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 5000
  		},
  		{
  			"id": 25856,
  			"name": "VERAERO_III",
  			"job": "RDM",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 5000
  		},
  		{
  			"id": 25860,
  			"name": "HOLY_III",
  			"job": "WHM",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 2500
  		},
  		{
  			"id": 25880,
  			"name": "SLEEP",
  			"job": "ROLE",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 2500
  		},
  		{
  			"id": 25883,
  			"name": "GEMSHINE",
  			"job": "SMN",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 2500
  		},
  		{
  			"id": 25884,
  			"name": "PRECIOUS_BRILLIANCE",
  			"job": "SMN",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 2500
  		},
  		{
  			"id": 34620,
  			"name": "DREADWINDER",
  			"job": "VPR",
  			"recast": 3000
  		},
  		{
  			"id": 34621,
  			"name": "HUNTERS_COIL",
  			"job": "VPR",
  			"recast": 3000,
  			"speedAttribute": "SKILL_SPEED"
  		},
  		{
  			"id": 34622,
  			"name": "SWIFTSKINS_COIL",
  			"job": "VPR",
  			"recast": 3000,
  			"speedAttribute": "SKILL_SPEED"
  		},
  		{
  			"id": 34623,
  			"name": "PIT_OF_DREAD",
  			"job": "VPR",
  			"recast": 3000
  		},
  		{
  			"id": 34624,
  			"name": "HUNTERS_DEN",
  			"job": "VPR",
  			"recast": 3000,
  			"speedAttribute": "SKILL_SPEED"
  		},
  		{
  			"id": 34625,
  			"name": "SWIFTSKINS_DEN",
  			"job": "VPR",
  			"recast": 3000,
  			"speedAttribute": "SKILL_SPEED"
  		},
  		{
  			"id": 34626,
  			"name": "REAWAKEN",
  			"job": "VPR",
  			"recast": 2200,
  			"speedAttribute": "SKILL_SPEED"
  		},
  		{
  			"id": 34627,
  			"name": "FIRST_GENERATION",
  			"job": "VPR",
  			"recast": 2000,
  			"speedAttribute": "SKILL_SPEED"
  		},
  		{
  			"id": 34628,
  			"name": "SECOND_GENERATION",
  			"job": "VPR",
  			"recast": 2000,
  			"speedAttribute": "SKILL_SPEED"
  		},
  		{
  			"id": 34629,
  			"name": "THIRD_GENERATION",
  			"job": "VPR",
  			"recast": 2000,
  			"speedAttribute": "SKILL_SPEED"
  		},
  		{
  			"id": 34630,
  			"name": "FOURTH_GENERATION",
  			"job": "VPR",
  			"recast": 2000,
  			"speedAttribute": "SKILL_SPEED"
  		},
  		{
  			"id": 34631,
  			"name": "OUROBOROS",
  			"job": "VPR",
  			"recast": 3000,
  			"speedAttribute": "SKILL_SPEED"
  		},
  		{
  			"id": 34633,
  			"name": "UNCOILED_FURY",
  			"job": "VPR",
  			"recast": 3500,
  			"speedAttribute": "SKILL_SPEED"
  		},
  		{
  			"id": 34653,
  			"name": "BLIZZARD_IN_CYAN",
  			"job": "PCT",
  			"recast": 3300,
  			"speedAttribute": "SPELL_SPEED"
  		},
  		{
  			"id": 34654,
  			"name": "STONE_IN_YELLOW",
  			"job": "PCT",
  			"recast": 3300,
  			"speedAttribute": "SPELL_SPEED"
  		},
  		{
  			"id": 34655,
  			"name": "THUNDER_IN_MAGENTA",
  			"job": "PCT",
  			"recast": 3300,
  			"speedAttribute": "SPELL_SPEED"
  		},
  		{
  			"id": 34659,
  			"name": "BLIZZARD_II_IN_CYAN",
  			"job": "PCT",
  			"recast": 3300,
  			"speedAttribute": "SPELL_SPEED"
  		},
  		{
  			"id": 34660,
  			"name": "STONE_II_IN_YELLOW",
  			"job": "PCT",
  			"recast": 3300,
  			"speedAttribute": "SPELL_SPEED"
  		},
  		{
  			"id": 34661,
  			"name": "THUNDER_II_IN_MAGENTA",
  			"job": "PCT",
  			"recast": 3300,
  			"speedAttribute": "SPELL_SPEED"
  		},
  		{
  			"id": 34663,
  			"name": "COMET_IN_BLACK",
  			"job": "PCT",
  			"recast": 3300,
  			"speedAttribute": "SPELL_SPEED"
  		},
  		{
  			"id": 34664,
  			"name": "POM_MOTIF",
  			"job": "PCT",
  			"recast": 4000,
  			"castTime": 3000
  		},
  		{
  			"id": 34665,
  			"name": "WING_MOTIF",
  			"job": "PCT",
  			"recast": 4000,
  			"castTime": 3000
  		},
  		{
  			"id": 34666,
  			"name": "CLAW_MOTIF",
  			"job": "PCT",
  			"recast": 4000,
  			"castTime": 3000
  		},
  		{
  			"id": 34667,
  			"name": "MAW_MOTIF",
  			"job": "PCT",
  			"recast": 4000,
  			"castTime": 3000
  		},
  		{
  			"id": 34668,
  			"name": "HAMMER_MOTIF",
  			"job": "PCT",
  			"recast": 4000,
  			"castTime": 3000
  		},
  		{
  			"id": 34669,
  			"name": "STARRY_SKY_MOTIF",
  			"job": "PCT",
  			"recast": 4000,
  			"castTime": 3000
  		},
  		{
  			"id": 34688,
  			"name": "RAINBOW_DRIP",
  			"job": "PCT",
  			"recast": 6000,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 4000
  		},
  		{
  			"id": 34689,
  			"name": "CREATURE_MOTIF",
  			"job": "PCT",
  			"recast": 4000,
  			"castTime": 3000
  		},
  		{
  			"id": 34690,
  			"name": "WEAPON_MOTIF",
  			"job": "PCT",
  			"recast": 4000,
  			"castTime": 3000
  		},
  		{
  			"id": 34691,
  			"name": "LANDSCAPE_MOTIF",
  			"job": "PCT",
  			"recast": 4000,
  			"castTime": 3000
  		},
  		{
  			"id": 36940,
  			"name": "STEELED_MEDITATION",
  			"job": "MNK",
  			"recast": 1000
  		},
  		{
  			"id": 36942,
  			"name": "FORBIDDEN_MEDITATION",
  			"job": "MNK",
  			"recast": 1000
  		},
  		{
  			"id": 36943,
  			"name": "ENLIGHTENED_MEDITATION",
  			"job": "MNK",
  			"recast": 1000
  		},
  		{
  			"id": 36978,
  			"name": "BLAZING_SHOT",
  			"job": "MCH",
  			"recast": 1500
  		},
  		{
  			"id": 36982,
  			"name": "FULL_METAL_FIELD",
  			"job": "MCH",
  			"recast": 2500
  		},
  		{
  			"id": 36989,
  			"name": "FLARE_STAR",
  			"job": "BLM",
  			"recast": 2500,
  			"speedAttribute": "SPELL_SPEED",
  			"castTime": 3000
  		},
  		{
  			"id": 37006,
  			"name": "GRAND_IMPACT",
  			"job": "RDM",
  			"recast": 2500
  		},
  		{
  			"id": 37034,
  			"name": "EUKRASIAN_PROGNOSIS_II",
  			"job": "SGE",
  			"recast": 1500
  		},
  		{
  			"id": 45960,
  			"name": "MANAFICATION_ENCHANTED_RIPOSTE",
  			"job": "RDM",
  			"recast": 1500
  		},
  		{
  			"id": 45961,
  			"name": "MANAFICATION_ENCHANTED_ZWERCHHAU",
  			"job": "RDM",
  			"recast": 1500
  		},
  		{
  			"id": 45962,
  			"name": "MANAFICATION_ENCHANTED_REDOUBLEMENT",
  			"job": "RDM",
  			"recast": 2200,
  			"speedAttribute": "SKILL_SPEED"
  		}
  	],
  	"speedStatuses": [
  		{
  			"id": 157,
  			"name": "PRESENCE_OF_MIND",
  			"job": "WHM",
  			"speedModifier": 0.8
  		},
  		{
  			"id": 738,
  			"name": "CIRCLE_OF_POWER",
  			"job": "BLM",
  			"speedModifier": 0.85
  		},
  		{
  			"id": 1299,
  			"name": "FUKA",
  			"job": "SAM",
  			"speedModifier": 0.87
  		},
  		{
  			"id": 3669,
  			"name": "SWIFTSCALED",
  			"job": "VPR",
  			"speedModifier": 0.85
  		},
  		{
  			"id": 3689,
  			"name": "INSPIRATION",
  			"job": "PCT",
  			"speedModifier": 0.75,
  			"limitedTo": [
  				34650,
  				34651,
  				34652,
  				34653,
  				34654,
  				34655,
  				34656,
  				34657,
  				34658,
  				34659,
  				34660,
  				34661,
  				34681
  			]
  		}
  	],
  	"onGcd": [
  		9, 15, 16, 21, 24, 31, 37, 41, 42, 45, 46, 53, 54, 56, 61, 62,
  		66, 70, 74, 75, 78, 84, 86, 87, 88, 90, 97, 98, 100, 106, 111, 113,
  		119, 120, 121, 124, 125, 127, 128, 131, 132, 133, 135, 137, 139, 141, 142, 147,
  		152, 153, 154, 156, 159, 162, 173, 185, 186, 190, 2240, 2242, 2247, 2254, 2255, 2259,
  		2260, 2261, 2263, 2265, 2266, 2267, 2268, 2269, 2270, 2271, 2272, 2866, 2868, 2870, 2872, 2873,
  		3538, 3539, 3541, 3543, 3545, 3549, 3550, 3554, 3556, 3560, 3563, 3568, 3572, 3576, 3577, 3579,
  		3584, 3594, 3595, 3596, 3598, 3599, 3600, 3601, 3603, 3608, 3610, 3615, 3617, 3621, 3623, 3624,
  		3632, 4262, 7381, 7384, 7391, 7392, 7397, 7406, 7407, 7409, 7410, 7411, 7412, 7413, 7418, 7420,
  		7422, 7426, 7427, 7431, 7435, 7442, 7477, 7478, 7479, 7480, 7481, 7482, 7484, 7485, 7486, 7487,
  		7488, 7489, 7497, 7503, 7504, 7505, 7507, 7509, 7510, 7511, 7512, 7513, 7514, 7516, 7523, 7524,
  		7525, 7526, 7527, 7528, 7529, 7530, 7568, 7867, 15989, 15990, 15991, 15992, 15993, 15994, 15995, 15996,
  		15997, 15998, 15999, 16000, 16001, 16002, 16003, 16004, 16005, 16137, 16139, 16141, 16143, 16145, 16146, 16149,
  		16153, 16162, 16163, 16191, 16192, 16193, 16194, 16195, 16196, 16230, 16457, 16458, 16459, 16460, 16462, 16463,
  		16465, 16468, 16473, 16476, 16477, 16479, 16483, 16485, 16486, 16488, 16491, 16492, 16494, 16495, 16496, 16497,
  		16498, 16499, 16500, 16504, 16505, 16506, 16507, 16514, 16515, 16524, 16525, 16526, 16528, 16529, 16530, 16531,
  		16532, 16533, 16534, 16535, 16539, 16540, 16541, 16554, 16555, 17206, 17215, 17216, 17865, 17870, 18805, 18806,
  		18807, 18873, 18874, 18875, 18876, 18877, 18878, 18879, 18880, 18881, 24283, 24284, 24286, 24287, 24289, 24290,
  		24291, 24292, 24293, 24297, 24304, 24306, 24307, 24308, 24312, 24313, 24314, 24315, 24316, 24318, 24373, 24374,
  		24375, 24376, 24377, 24378, 24379, 24380, 24381, 24382, 24383, 24384, 24385, 24386, 24387, 24388, 24395, 24396,
  		24397, 24398, 25748, 25749, 25750, 25753, 25760, 25764, 25765, 25767, 25768, 25769, 25770, 25771, 25772, 25774,
  		25775, 25777, 25778, 25780, 25781, 25782, 25783, 25784, 25786, 25788, 25790, 25792, 25793, 25794, 25795, 25797,
  		25798, 25805, 25806, 25807, 25814, 25815, 25816, 25817, 25818, 25819, 25820, 25821, 25822, 25823, 25824, 25825,
  		25826, 25831, 25832, 25833, 25834, 25835, 25837, 25838, 25839, 25840, 25855, 25856, 25858, 25859, 25860, 25865,
  		25866, 25871, 25872, 25874, 25880, 25882, 25883, 25884, 25885, 34606, 34607, 34608, 34609, 34610, 34611, 34612,
  		34613, 34614, 34615, 34616, 34617, 34618, 34620, 34621, 34622, 34623, 34624, 34625, 34626, 34627, 34628, 34629,
  		34630, 34631, 34632, 34633, 34650, 34651, 34652, 34653, 34654, 34655, 34656, 34657, 34658, 34659, 34660, 34661,
  		34662, 34663, 34664, 34665, 34666, 34667, 34668, 34669, 34678, 34679, 34680, 34681, 34688, 34689, 34690, 34691,
  		36918, 36919, 36925, 36928, 36929, 36930, 36931, 36932, 36938, 36939, 36940, 36942, 36943, 36945, 36946, 36947,
  		36948, 36949, 36950, 36952, 36954, 36955, 36963, 36970, 36971, 36972, 36973, 36976, 36977, 36978, 36981, 36982,
  		36983, 36984, 36985, 36986, 36987, 36989, 36992, 36994, 36995, 37002, 37003, 37004, 37006, 37009, 37010, 37013,
  		37015, 37016, 37030, 37032, 37034, 45960, 45961, 45962
  	]
  };
});
